In [8]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [9]:
data = pd.read_csv("../murders-feature-selected.csv")
display(data)

,Relationship,Solved,OffSex,Situation,Circumstance,OffEthnic,VicSex,Weapon,AgentType,Source,YearInterval,OffAge,VicRace,State,OffRace,Homicide
0,1,1,1,0,24,0,2,8,3,0,0,55,0,1,0,1
1,1,1,2,0,12,0,2,15,1,0,0,67,2,0,2,1
2,1,1,2,0,22,0,1,15,1,0,0,53,2,0,2,1
3,1,1,1,0,24,0,2,8,1,0,0,35,2,0,2,1
4,1,1,1,0,10,0,2,16,1,0,0,25,5,0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868475,1,1,2,4,21,1,2,7,5,0,2,26,5,50,5,1
868476,1,1,2,0,1,1,1,9,1,0,2,34,5,50,5,0
868477,1,1,2,4,22,1,1,7,1,0,2,51,5,50,5,1
868478,1,1,2,4,22,1,1,7,1,0,2,51,5,50,5,1
868479,1,1,2,0,24,1,1,7,5,0,2,50,5,50,5,1

In [10]:
data["Relationship"] = data["Relationship"].astype("category")

In [11]:
X = data.drop("Relationship", axis=1)
y = data["Relationship"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
c45_model = DecisionTreeClassifier()
c45_model.fit(X_train, y_train)
c45_pred = c45_model.predict(X_test)

In [14]:
c45_accuracy = accuracy_score(y_test, c45_pred)
print("C4.5 Accuracy:", c45_accuracy)

C4.5 Accuracy: 0.7986520510930976